networks:
  my-network:
    driver: bridge
services:
  nginx:
    container_name: ${PROJECT_NAME}-nginx
    image: nginx:alpine
    networks:
      - my-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/app
      - ./public:/var/www/html
      - ./vendor:/var/www/vendor
      - ./.env:/var/www/.env
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-php
    image: php:fpm-alpine
    networks:
      - my-network
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/app
      - ./public:/var/www/html
      - ./vendor:/var/www/vendor
      - ./.env:/var/www/.env
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    image: mysql:latest
    networks:
      - my-network
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
  phpmyadmin:
    container_name: ${PROJECT_NAME}-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - my-network
    ports:
      - 8080:80
      